README.md, pydantic_factories/exceptions.py, pydantic_factories/factory.py, tests/test_factory_build.py
Added a new param to build function to allow building a pydantic model without validating input using the construct method as discussed [here](https://github.com/Goldziher/pydantic-factories/issues/15)
=> allow building a model without validating input

.pre-commit-config.yaml, mypy.ini, pydantic_factories/factory.py, pydantic_factories/protocols.py, pydantic_factories/strict_typing_check.py, tests/typing_test_strict.py
Using a factory in mypy strict requires a typed generic and providing
the model itself as the generic type did not work because contrained
TypeVar doesn't allow subclassing, as a bound TypeVar allows it.
A file with this typing with its own mypy config was added to test the
behaviour remains.   Adding this showed that the DataclassProtocol
was too narrow as a single field dataclass does not have
`__dataclass_params__` and `__post_init__` attributes and it seems
that marking them as Optional is not enough.
**EDIT** BONUS: fix exclusion regex in pre-commit
Fixes #21
**EDIT** This is fixed, was an issue with the exclusion regex.
~I added a test for this...  I really tried hard to put the `pydantic_factories/strict_typing_check.py` file in the tests folder but i just couldn't figure out how …
=> Use TypeVar's bound instead of constraint

pydantic_factories/constraints/constrained_collection_handler.py, pydantic_factories/extensions/ormar_orm.py, pydantic_factories/factory.py, pydantic_factories/utils.py, pydantic_factories/value_generators/complex_types.py, pydantic_factories/value_generators/constrained_number.py, pydantic_factories/value_generators/primitives.py, tests/test_random_seed.py
This is a quick fix to be able to seed the `exrex` package
without having two different instances of the `Random` classes.
=> Use default random instance

pydantic_factories/factory.py, pyproject.toml, tests/test_factory_build.py
Consider the allow_population_by_field_name flag when building an instance from pydantic model
The allow_population_by_field_name flag participates in making a decision about using an alias field name
=> Recognize the allow_population_by_field_name flag

CHANGELOG.md, pydantic_factories/factory.py, tests/test_factory_child_models.py
This aims to solve issue #61.
Partial attributes factory for Mapping fields will not be supported yet as it requires a more advanced data manipulation.
This means that given the following models:
```python
class NestedSchema(BaseModel):
v: str
z: int
class UpperSchema(BaseModel):
a: int
b: Mapping[str, str]
nested: Mapping[str, NestedSchema]
class NestedSchemaFactory(ModelFactory):
__model__ = NestedSchema
class UpperSchemaFactory(ModelFactory):
__model__ = UpperSchema
```
The case of the issue will work fine:
```python
def test_factory_not_ok():
nested = NestedSchema(v="hello", z=0)
some_dict = {"test": "fine"}
upper = UpperSchemaFactory.build(b=some_dict, nested={"nested": nested})
```
But no support is given yet for:
```python
def test_factory_not_ok():
nested = NestedSchema(v="hello", …
```
=> Fix error when building Pydantic models with Mapping fields [Issue #61]

pydantic_factories/__init__.py, pydantic_factories/plugins/__init__.py
Pytest is generally unavailable when the library is used outside of testing context.
Closes #77
=> Removes top-level imports of pytest plugin.

CHANGELOG.md
Reorder changes in the CHANGELOG file so the newest version is on top
=> docs: reorder changes in CHANGELOG

pydantic_factories/factory.py
=> Fix doc-string typo in ModelFactory.build

pydantic_factories/factory.py, tests/test_factory_build.py
=> Fix factories not allowing to build when models have fields with similar keys to `ModelFactory` fields.

.github/workflows/ci.yaml, .pre-commit-config.yaml, CHANGELOG.md, mypy.ini, poetry.lock, pydantic_factories/constraints/strings.py, pydantic_factories/value_generators/regex.py, pyproject.toml, tests/test_refex_factory.py
This PR replace `Xeger`, which has not been updated for 2 years and is not compatible with py 3.11. It does additional housekeeping.
=> Replace Xeger

CHANGELOG.md, pydantic_factories/factory.py, tests/test_factory_child_models.py
This aims to solve a very similar to the previously reported issue https://github.com/starlite-api/pydantic-factories/issues/61.
This PR aims to fix the same error for the Dict field. An example case is shown below
```
class NestedSchema(BaseModel):
z: int
class UpperSchema(BaseModel):
nested: Mapping[str, NestedSchema]
class NestedSchemaFactory(ModelFactory):
__model__ = NestedSchema
class UpperSchemaFactory(ModelFactory):
__model__ = UpperSchema
```
This will not work as intended and the explicitly set nested field will be respected during the build call
```
def test_dict_factory_not_ok():
nested = NestedSchema(z=0)
upper = UpperSchemaFactory.build(nested={"nested": nested})
```
=> Fix error when building Pydantic models with nested Dict field

pydantic_factories/value_generators/regex.py
There doesn't seem to be a public api for this moving forward, but apparently `sre_parse` was undocumented anyway.
References:
- https://github.com/HypothesisWorks/hypothesis/pull/3310/commits/6d1d17d016d092146b620e4f9338f9b125e33ded
- https://github.com/scikit-hep/awkward/pull/1548/files
- https://github.com/leapfrogonline/rstr/pull/28/files
=> Fixes deprecation warning for `sre_parse` on 3.11.

pydantic_factories/factory.py, tests/test_factory_child_models.py
This PR closes #115 
Here I use recursion and do not apply caching decorators for the sake of keeping the code as simple as possible.
My initial attempt was to go with a proper iterative tree walk and caching but the resulting code became hard to read. A performance impact for not using cache appears with really deeply nested models and kwargs and I am not sure that our users would be using the library this way (I can not image someone sane doing MyModelFactory.build(**{...{... { .. }}})) with at least 15 levels of deepness).
=> Fix partial kwargs detection for deeply nested models

.github/workflows/ci.yaml, .pre-commit-config.yaml, poetry.lock, pydantic_factories/plugins/pytest_plugin.py, pydantic_factories/protocols.py, pyproject.toml, tests/test_data_parsing.py, tests/test_discriminated_unions.py
We follow Python version support policy of Starlite and drop Python 3.7 support as well.
Also this PR updates versions in pre-commit config to match version in Starlite's pre-commit config.
=> Drop Python 3.7 support

.pre-commit-config.yaml, pydantic_factories/value_generators/constrained_number.py, tests/constraints/test_decimal_constraints.py
I had to keep pyright at 1.1.280 in #126 because 1.1.281 didn't type check `generate_constrained_number` with Callable.
This PR improves typing of the function and upgades pyright to the latest version.
=> Improve typing for internal number generator

pydantic_factories/extensions/ormar_orm.py, tests/extensions/test_ormar_extension.py
Closes #128 
For some reason when setting `model_field.required` other attributes are resetted. So the best solution I was to able to come up is using deepcopy on `model_field` if we are going to set `required` to True. Everything else I tried failed on other stages damaging the initial model.
=> Do deepcopy for ormar fields we mark as required

polyfactory/fields.py
Fixes #164 by removing the hard dependency on pytest. Pytest will now only be imported when the `Fixture` field is being used.
=> Fix #164: Remove hard pytest dependency

.github/workflows/ci.yaml
Remove the `restore-keys` directive for the venvs cache, since this seems to lead to broken venvs quite frequently.
=> CI: Remove `restore-keys` for venv cache

polyfactory/constants.py, polyfactory/field_meta.py, tests/test_dataclass_factory.py
User claims that `tuple[int, ...]` doesn't work with `dataclasses`. I've added a test and it's true. It works however for `pydantic`, because `pydantic` doesn't return Ellipsis' in fields representation.
I've added a test that fails for given scenario. I've then added a set of types to ignore.
[//]: # "Please add …
=> Make polyfactory work with Ellipsis in dataclasses

README.md, polyfactory/factories/base.py, tests/test_factory_subclassing.py
- ~[ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR~
- ~[ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR~
Fix error message when model type is not supported:
```
polyfactory.exceptions.ConfigurationException: Model type …
```
=> Fix missing f-string when raising `ConfigurationException` for unsupported model type

polyfactory/factories/base.py, polyfactory/factories/odmantic_odm_factory.py, polyfactory/factories/pydantic_factory.py, tests/test_odmantic_factory.py
Support bson fields for `odmantic` models.
~Currently in draft as it still fails for `odmantic.EmbeddedModel` due to a different issue: the selected factory for `odmantic.EmbeddedModel` is the (pydantic) `ModelFactory` instead of `OdmanticModelFactory`. Both these factories return True for `is_supported_type(model)` but the first one is picked instead of the second one [here](https://github.com/litestar-org/polyfactory/blob/main/polyfactory/factories/base.py#L292-L294).~
EDIT: fixed at c830ed5e0fadc5d3dc1d9461f7ac59428df74a9e
Fixes #192
=> Bson field support for odmantic models

polyfactory/utils/helpers.py, polyfactory/value_generators/complex_types.py, tests/test_dicts.py
Previously under pydantic-factory
values for a dictionary of union
were generated randomly based on
union types. Under the latest
version of polyfactory always the
first type is used. After that fix
everything is working like previously.
Test for that issue was added.
=> Fix: Random union types for dict

docs/examples/fields/test_example_7.py, polyfactory/factories/pydantic_factory.py, polyfactory/value_generators/complex_types.py, tests/test_complex_types.py, tests/test_constrained_attribute_parsing.py, tests/test_dicts.py
Several fixes related to complex types + overall refactoring of `complex_types.py` while at it.
1. [Fix](https://github.com/litestar-org/polyfactory/pull/202/commits/43553879e2a45d9c5d998f82d3f7eb0afe9b9b24) for generic container fields with unspecified type parameters, e.g. `List` instead of `List[Any]`. 
Currently raises `ParameterException: Unsupported type: ~T`
2. [Fix](https://github.com/litestar-org/polyfactory/pull/202/commits/1d1c721e64e0ca4ec10afd612e37eb2406324628) for Pydantic constrained mapping fields, e.g. `Dict[str, MyConstrainedInt]`.
Currently the factory ignores the constraint, resulting in ValidationError.
3. [Fix](https://github.com/litestar-org/polyfactory/pull/202/commits/caf7e0b16b88fabca26dbb41aa405a703e8e69b8) for custom generic fields that are not collections; …
=> Misc. fixes for complex types 

polyfactory/factories/pydantic_factory.py, tests/test_complex_types.py
Add support for https://docs.pydantic.dev/latest/usage/models/#custom-root-types, a Pydantic feature which allows for things such as root-level discriminated unions. This is achieved by specifying a "dummy" field called `__root__` which was considered …
=> Add support for custom root types in Pydantic model factory

polyfactory/factories/odmantic_odm_factory.py, tests/test_odmantic_factory.py
The `id` field of Odmantic models doesn't have to be specified as `Ignore`; its type is `bson.ObjectId` which has a default constructor so it can be autogenerated. By not ignoring it, it can be used as a dependency of `PostGenerated` fields as shown in the unit test.
=> Don't ignore the id field of odmantic models

polyfactory/value_generators/primitives.py, tests/constraints/test_int_constraints.py
=> Fix create_random_integer to include the upper bound

polyfactory/factories/pydantic_factory.py, tests/test_constrained_attribute_parsing.py
=> Fix PydanticFieldMeta.from_model_field() for Optional fields

polyfactory/factories/base.py, tests/constraints/test_get_field_value_constraints.py
Include the missing types in the creation of constrained field values which includes bytes, date, and tuples.
[//]: # "Examples: Fixes #4321 or Closes …
=> Include missing types in creating constrained field values

polyfactory/constants.py, polyfactory/field_meta.py
Adds a default value for the `FieldMeta` `random` args introduced in #222. They will default to a predefined, shared instance of `Random`.
=> Add a default value for `FieldMeta` `random` args

polyfactory/factories/pydantic_factory.py, tests/test_data_parsing.py
Unwrapping annotation for pydantic factories to ensure valid `if` comparison for optional `URL*` types
Fixes #234
=> Unwrap annotation for URL types (#234)

polyfactory/value_generators/complex_types.py, tests/test_complex_types.py
The issue described in #239 is fixed in this PR. The issue arises, because the generation of Literal field is handled directly in `polyfactory.factories.base.BaseFactory.get_field_value()`, but generating for a collection type uses …
=> Fix list of literal generation (#239)

polyfactory/factories/base.py, polyfactory/value_generators/complex_types.py
Returning a field value from a factory is currently handled by one of four different callables:
1. `BaseFactory.get_field_value`
2. `BaseFactory.get_mock_value`
3. `complex_types.handle_complex_type`
4. `complex_types.handle_collection_type`
Even worse, these callables may call each other recursively. The end result is complexity, bugs such as https://github.com/litestar-org/polyfactory/issues/239 and [code duplication](https://github.com/litestar-org/polyfactory/pull/240) to fix such bugs.
This PR merges (2) and (3) into (1), leaving just two callables in place of four.
=> Refactor base factory.get_field_value

polyfactory/factories/base.py, polyfactory/factories/dataclass_factory.py, polyfactory/factories/odmantic_odm_factory.py, polyfactory/factories/pydantic_factory.py, polyfactory/factories/typed_dict_factory.py, polyfactory/pytest_plugin.py, polyfactory/utils/predicates.py
- Extend `utils.predicates.is_safe_subclass` to accept tuple of classes just like regular `issubclass`
- Replace all `isclass(...) and issubclass(...)` expressions with `is_safe_subclass`
=> Use is_safe_subclass consistently

docs/conf.py, poetry.lock, polyfactory/factories/base.py, polyfactory/factories/pydantic_factory.py, polyfactory/field_meta.py, tests/constraints/test_list_constraints.py, tests/test_build.py, tests/test_complex_types.py, tests/test_constrained_attribute_parsing.py, tests/test_data_parsing.py, tests/test_dicts.py, tests/test_new_types.py, tests/test_odmantic_factory.py, tests/test_pydantic_factory.py, tests/test_random_seed.py
This PR fixes an issue with `const` not working for pydantic v1 factories. It also does some cleanup of pydantic related tests.
=> Fix `const` not being used with pydantic v1 models. 

docs/examples/declaring_factories/test_example_7.py, docs/reference/factories/attrs_factory.rst, docs/reference/factories/index.rst, docs/usage/declaring_factories.rst, docs/usage/library_factories.rst, poetry.lock, polyfactory/factories/attrs_factory.py, pyproject.toml, tests/test_attrs_factory.py
- [ x ] New code has 100% test coverage
- [ x ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ x  ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR
- [ x ] Pre-Commit Checks were ran and passed
- [ x ] Tests were ran and passed
- implementation of Attrs Factory
[//]: # "Please add in issue numbers this …
=> feat: implementation of Attrs Factory

polyfactory/value_generators/primitives.py, tests/test_random_seed.py
- `urandom` was replaced by using `random.getrandbits` to make generation of constrained strings deterministic when seed is set
Fixes #316
=> fix: constrained strings not deterministic with seed because urandom not seedable

CONTRIBUTING.rst, Makefile, polyfactory/factories/base.py, polyfactory/factories/pydantic_factory.py, polyfactory/utils/helpers.py, polyfactory/utils/predicates.py, tests/test_pydantic_factory.py
Hello! :wave: 
I had initially commented [here](https://github.com/litestar-org/polyfactory/issues/230#issuecomment-1659714195), but this was a separate issue. So I just went ahead and fixed it.
- Fix pydantic metadata parsing on optional field
=> fix: include pydantic Field constraints when using Optional type

polyfactory/factories/base.py, tests/test_data_parsing.py
- Adds the new (post v2) [Pydantic's AwareDatetime](https://docs.pydantic.dev/2.2/usage/types/datetime/#pydantic-date-types) type to the types map
-
=> feat: add pydantic's AwareDatetime to the mock map

.all-contributorsrc, .github/workflows/ci.yaml
- This PR ensures that the full Python version, including the minor version, is used for the venv caching.
=> fix: use full Python version for venv cache

polyfactory/field_meta.py, polyfactory/utils/predicates.py, tests/test_annotated_fields.py
- This PR ensures the constraints are properly parsed when using an optional with Annotated constraints in subtypes.
- Closes #317
=> fix: properly set annotation in union with Annotated constraints in subtypes

docs/examples/handling_custom_types/test_example_1.py
Previously you had to scroll to read the comment:
https://polyfactory.litestar.dev/usage/handling_custom_types.html
Now, it will be visible without scrolling.
=> docs: change the comment length in "Handling custom types" docs

poetry.lock, pyproject.toml
- This PR adds a minimum constraint to the attrs version since the current `AttrsFactory` implementation only works with `attrs` version 22.2.0 onwards.
- Fixes #356
=> fix: add minimum version constraint to attrs

pyproject.toml
It also removes this warning:
```
tests/test_attrs_factory.py:13
/Users/sobolev/Desktop/polyfactory/tests/test_attrs_factory.py:13: PytestUnknownMarkWarning: Unknown pytest.mark.attrs - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
pytestmark = [pytest.mark.attrs]
```
=> test: make `pytest` configuration stricter

.github/workflows/publish.yaml, CONTRIBUTING.rst
Enable publishing with [PyPI's trusted publishers](https://docs.pypi.org/trusted-publishers).
=> ci: Enable publishing with PyPI trusted publishers

docs/conf.py, polyfactory/factories/base.py
- This PR makes the type hints for `BaseFactory.create_factory` generic to allow type checkers to properly infer the type of the created factory.
- Fixes #358
=> fix: properly type hint create_factory

tests/test_odmantic_factory.py
- skip `tests/test_odmantic_factory::test_variable_length__dict` because it's very flaky (refer #362 for details)
=> test: skip variable length dict test for odmantic

polyfactory/factories/attrs_factory.py, polyfactory/factories/base.py, tests/test_attrs_factory.py
- don't register `AttrsFactory` by default
- properly resolve any strings or forward annotations in attrs models
- Fixes #356 and #364
=> fix: `AttrsFactory` fixes

polyfactory/fields.py, tests/test_pytest_plugin.py
- Fix fixture size handling for 0
- Fixes #143
=> fix: update fixture size handling

.pre-commit-config.yaml
- Contributers file is auto generated so breaks pre-commit checks
- Copying the approach in litestar repo here https://github.com/litestar-org/litestar/blob/main/.pre-commit-config.yaml#L51C1-L53C1
-
=> chore: ignore .all-contributorsrc for in .pre-commit

polyfactory/factories/dataclass_factory.py, polyfactory/utils/helpers.py, tests/test_dataclass_factory.py
- Get dataclass type information from field.type instead of using `typing.get_type_hints`
- Fixes https://github.com/litestar-org/polyfactory/issues/347
=> fix: Dataclass field type not used correctly

polyfactory/factories/dataclass_factory.py, polyfactory/utils/helpers.py, tests/test_dataclass_factory.py
This PR reverts #371 because the dataclasses `fields` API does not properly resolve the forward annotations as explained in this [issue](https://github.com/python/cpython/issues/80824). For getting the resolved types, we have to use `get_type_hints` though that doesn't work well with models like `MappedAsDataclass` of `sqlalchemy`. For those cases, it's probably better for users to subclass the current …
=> fix: properly resolve dataclass forward references

.github/workflows/ci.yaml, pdm.lock, pyproject.toml
[//]: # "- follow the [PSFs's Code of Conduct](https://www.python.org/psf/conduct/)"
- Ensure correct version is installed
- Add extra cache file to ensure distinct caches
- Change to `pdm sync` to ensure packages aren't updated with install.
- Closes #388
=> fix: fix alternative version installation

polyfactory/factories/base.py, polyfactory/factories/pydantic_factory.py, tests/test_provider_map.py
[//]: # "- follow the [PSFs's Code of Conduct](https://www.python.org/psf/conduct/)"
- move creation of pydantic provider map
=> refactor: move creation of pydantic provider map

polyfactory/factories/base.py, polyfactory/field_meta.py, polyfactory/utils/helpers.py, tests/test_attrs_factory.py, tests/test_beanie_factory.py, tests/test_collection_length.py, tests/test_dataclass_factory.py, tests/test_msgspec_factory.py, tests/test_odmantic_factory.py, tests/test_passing_build_args_to_child_factories.py, tests/test_typeddict_factory.py
- this handles the cases where `__min_collection_length__` or `__max_collection_length__` are set in the `get_field_value` method directly instead of coupling these constraints into the created `FieldMeta` instances
- Fixes #403
=> fix: decouple the handling of collection length configuration from `FieldMeta`

polyfactory/factories/msgspec_factory.py
- use the `fields` API as suggested [here](https://github.com/jcrist/msgspec/pull/566#pullrequestreview-1671507706)
- don't repeatedly call `get_type_hints`
=> refactor: refactor the msgspec factory to use the fields API

docs/examples/configuration/test_example_8.py, docs/usage/configuration.rst, docs/usage/declaring_factories.rst, polyfactory/factories/base.py, polyfactory/warning_categories.py, tests/test_factory_fields.py
This change will detect whenever a field is defined on the factory that doesn't exist on the model.
- If the field is using an explicit construct (like `Use`, `PostGenerated`, ...) it will raise an exception
- in other case it will only output a warning
- classmethods / methods / functions and fields starting with `__`  are not checked because they can't be easily differentiated
Fixes #400
-
=> feat: check if fields declared on the factory belong to the model

polyfactory/factories/attrs_factory.py, polyfactory/factories/dataclass_factory.py, polyfactory/factories/msgspec_factory.py, polyfactory/factories/pydantic_factory.py, polyfactory/factories/sqlalchemy_factory.py, polyfactory/factories/typed_dict_factory.py, polyfactory/field_meta.py, polyfactory/utils/deprecation.py, tests/utils/test_deprecation.py
- Vendor in https://github.com/litestar-org/litestar/blob/main/litestar/utils/deprecation.py#L71, adjust and add parameter util.
- Deprecate collection params for FieldMeta
- Update PydanticFieldMeta implementation. This harmonises usage with other FieldMeta and think extending is implicitly ignored right now
- Closes #415
=> feat: deprecate FieldMeta collection params

polyfactory/factories/typed_dict_factory.py, tests/constraints/test_int_constraints.py, tests/test_typeddict_factory.py
- properly handle `Required` and `NonRequired` annotations
- Fixes #421
=> fix: handle Required and NonRequired annotations

polyfactory/factories/base.py, tests/test_build.py, tests/test_passing_build_args_to_child_factories.py
- Fixes `None` being randomly assigned to optional fields whose type is another model even if attributes for that model are passed to `build` as a `dict`
- Closes #419
---
I tried to mimic the structure of other tests on the file but open to feedback. The code change makes sense to me (if there are build parameters defined for a given field, don't consider setting it to `None`) but there might be other code paths I'm not considering.
=> fix: respect override of optional nested model fields

docs/examples/declaring_factories/test_example_8.py, docs/usage/declaring_factories.rst, polyfactory/factories/base.py, tests/test_base_factories.py
This PR aims at allowing to create "sub" factories from concrete factories (i.e: a factory with a `__model__` set) without having to pass the `model` argument to the `create_factory` method.
In this case, when the `model` argument is omitted, the `__model__` of the receiving factory will be used by default, increasing code readability and making the dynamic mode working the same way as the imperative style.
>The PR includes the change, the tests and the documentation update.
```python
from dataclasses import dataclass
from polyfactory.factories import DataclassFactory
@dataclass
class Foo:
bar: str
class FooFactory(DataclassFactory):
__model__ = Foo
class BarFactory(FooFactory):
bar = "bar"
foo_factory = DataclassFactory.create_factory(Foo)
bar_factory = …
```
=> feat: autofill `model` argument when calling `create_factory` with receiving factory `__model__`

polyfactory/factories/attrs_factory.py, polyfactory/factories/dataclass_factory.py, tests/test_attrs_factory.py, tests/test_dataclass_factory.py
- This PR checks if the `init` value is set to `False` for dataclasses and attrs models before creating the field metas
- Fixes #416
=> fix: handle cases where 'init=False' for dataclasses and attrs models

polyfactory/factories/pydantic_factory.py, polyfactory/field_meta.py, polyfactory/utils/helpers.py, tests/test_msgspec_factory.py, tests/test_pydantic_factory.py
This PR ensures that the constraints for subitems in collection types are parsed correctly.
- Fixes #434.
=> fix: correctly handle collections with constrained items  

polyfactory/utils/helpers.py, tests/test_type_coverage_generation.py
`polyfactoryutils.helpers.flatten_annotation` does not handle Optional properly
Fixes: #439
=> fix: flatten_annotation behaviour for Optional

polyfactory/factories/base.py
The suppressing of `ValueError` even when it's raised from `get_constrained_collection` or `get_constrained_dict` causes the exception to be thrown to be misleading. This fixes that by only catching the `ValueError` if it was raised from `get_collection_type`.
- Fixes #449.
=> fix: don't blindly suppress ValueError

pdm.lock, pyproject.toml
Add minimum `typing-extensions` version in dependencies.
Closes #470
=> fix: add min version to typing-extensions

docs/examples/configuration/test_example_9.py, docs/usage/configuration.rst, polyfactory/factories/base.py, tests/test_attrs_factory.py, tests/test_dataclass_factory.py, tests/test_msgspec_factory.py, tests/test_pydantic_factory.py
- This PR allows users to configure whether to use the default value for a field or not based on the `__use_defaults__` field on the class.
- Users can also have more fine-grained (i.e. per field) control by overriding `BaseFactory.should_use_default_value` classmethod.
- Closes #466.
=> feat: allow use of the default value based on configuration

docs/usage/handling_custom_types.rst, polyfactory/factories/base.py, polyfactory/factories/sqlalchemy_factory.py, tests/test_factory_configuration.py
- 
- Fixes #318 
- Fixes #424 
- FIxes #426
=> feat: pass on factory config

.github/workflows/ci.yaml, .github/workflows/docs.yaml, .github/workflows/publish.yaml, .pre-commit-config.yaml, polyfactory/utils/helpers.py, polyfactory/utils/predicates.py, pyproject.toml, tests/test_new_types.py
- Add Python 3.12 to python and update targets.
- Support type soft keyword.
- Fixes #455
=> feat: support type alias

polyfactory/factories/pydantic_factory.py, pyproject.toml, tests/constraints/test_date_constraints.py, tests/constraints/test_decimal_constraints.py, tests/constraints/test_list_constraints.py, tests/test_annotated_fields.py, tests/test_base_factories.py, tests/test_build.py, tests/test_collection_length.py, tests/test_complex_types.py, tests/test_constrained_attribute_parsing.py, tests/test_data_parsing.py, tests/test_dicts.py, tests/test_factory_fields.py, tests/test_factory_subclassing.py, tests/test_new_types.py, tests/test_optional_model_field_inference.py, tests/test_options_validation.py, tests/test_persistence_handlers.py, tests/test_pydantic_factory.py, tests/test_pydantic_v1_v2.py, tests/test_pytest_plugin.py, tests/test_recursive_models.py, tests/test_setting_default_factories.py, tests/test_typeddict_factory.py, tests/test_union_handling.py, tests/test_utils.py
Pydantic v2 allows for using both v2 and v1 models at the same time. This PR changes the logic in the `ModelFactory` to allow for that.
- Closes #446.
=> feat: support Pydantic v1 and v2 simultaneously

docs/usage/configuration.rst
Checked these since it's vacuously true, as there's no new code
The ClassVar is named `__use_defaults__` but the doc page currently mentions `__use_default__`
N/A
=> docs: fix typo on use_defaults

polyfactory/factories/sqlalchemy_factory.py
This PR checks for the `impl` property before default to `type.python_type`.
This is the documented way to use the [`sqlalchemy.types.TypeDecorator`](https://docs.sqlalchemy.org/en/20/core/custom_types.html#augmenting-existing-types)
=> fix: prefer `sqlalchemy.type.impl` if it exists

polyfactory/constants.py, polyfactory/factories/pydantic_factory.py, polyfactory/field_meta.py, polyfactory/value_generators/complex_types.py, tests/test_msgspec_factory.py, tests/test_pydantic_factory.py
- Fix the parsing of the constraints from union types for Pydantic v2 models
- Before there used to be special handling of optional types, but that's not needed since optional types are also unions and so optional types should also be handled the same way as union types where we just ignore `NoneType`. This makes the change the same as that of `FieldMeta.from_type` (as changed in #491).
- Fix the way the annotated types are handled when calling `FieldMeta.from-type` by using the actual type that is annotated rather than `Annotated[type, ...]`
- Due to the change in `FieldMeta.type_args` in #491, `Annotated[List[str], MinLen(10)]` now returns `List[str]` whereas before it would have returned `str` as the child. This results in the children for the `FieldMeta` corresponding to the …
=> fix: constrained unions

polyfactory/factories/sqlalchemy_factory.py, tests/sqlalchemy_factory/test_sqlalchemy_factory_common.py
=> fix: favour SA mapped type over impl type

.pre-commit-config.yaml, docs/examples/decorators/test_example_1.py, polyfactory/factories/base.py, polyfactory/factories/beanie_odm_factory.py, polyfactory/factories/pydantic_factory.py, polyfactory/value_generators/constrained_dates.py, tests/test_random_configuration.py, tests/test_recursive_models.py
=> fix: update typing

polyfactory/factories/sqlalchemy_factory.py, tests/sqlalchemy_factory/test_sqlalchemy_factory_common.py
Use Case: column use `server_default` to generate default value in database side.
If we use asyncsession, and access this attribute from orm object, it will raise `sqlalchemy.exc.MissingGreenlet` error.
There are two ways to solve this issue.
- the first one, refresh it directly after commit (choice this one in this PR, which may add very little latency)
- the second one, add params `refresh` to `create_async()` and `create_batch_async()` and default value is False. it will depends user's input in creation object.
=> feat(sqla_factory): refresh object in async_session after commit to db

docs/conf.py
- Adds a link to the GitHub repository to the docs page. Follows a similar PR done here https://github.com/litestar-org/advanced-alchemy/pull/191
Current
After
=> docs(config): link to GitHub repo

polyfactory/factories/base.py, tests/test_provider_map.py
- We were incorrectly not considering the value provided in the provider map for any field typed as `Any.` This ensures that we consider the value given in the provider map allowing users to override the generated value.
- This also fixes the same issue that may arise if the user wishes to override the value generated for `TypeVar`.
- Fixes #521.
=> fix: use provider map for generating value for 'Any'

polyfactory/value_generators/constrained_collections.py, tests/constraints/test_frozen_set_constraints.py, tests/constraints/test_list_constraints.py, tests/constraints/test_set_constraints.py
=> fix: constrained 0 length lists

.pre-commit-config.yaml, pdm.lock, polyfactory/factories/base.py, polyfactory/factories/pydantic_factory.py, polyfactory/factories/sqlalchemy_factory.py, polyfactory/factories/typed_dict_factory.py, polyfactory/field_meta.py, polyfactory/pytest_plugin.py, polyfactory/utils/model_coverage.py, polyfactory/utils/predicates.py, polyfactory/value_generators/regex.py, tests/test_type_coverage_generation.py
- Update precommit and linting dependencies
- Main code changes is formatting errors and error code changes
Closes #518
=> build: update pre-commit dependencies

polyfactory/factories/base.py, tests/test_provider_map.py
Update coverage to match https://github.com/litestar-org/polyfactory/pull/522
=> fix: use provider map for any in coverage

polyfactory/collection_extender.py, polyfactory/factories/base.py, polyfactory/field_meta.py, polyfactory/utils/helpers.py, polyfactory/value_generators/complex_types.py, tests/test_dataclass_factory.py
- Currently, tuple with fixed length and randomised collection length are not handled correctly. These are treated as arbitary length tuples.
- Remove calls to collection extender so this type is explicitly passed to other places.
- Fixes #553 
- Fixes #572
=> fix: tuple randomized length

docs/usage/declaring_factories.rst
It looks like the original intention was to use word "declaratively" to describe this kind of code:
```python
class PersonFactory(DataclassFactory[Person]):
__model__ = Person
```
=> docs: swap word with its antonym to match the context

polyfactory/value_generators/constrained_collections.py, tests/test_collection_length.py, tests/test_complex_types.py
For `Set[Enum]` fields with a limited maximum length, adjust `min_items` and `max_items` to be within the range of valid lengths.
Fixes #565
=> fix: Adjust min/max items to valid lengths for Set[Enum] fields

polyfactory/factories/base.py, tests/test_recursive_models.py
- Handle case based on doc string
Partially fixes #583
=> fix: handle Optional type recursive models

polyfactory/value_generators/complex_types.py, polyfactory/value_generators/constrained_collections.py, tests/test_recursive_models.py
=> fix: handle recursive collections

docs/changelog.rst, pyproject.toml
=> chore(release): bump release version

polyfactory/factories/sqlalchemy_factory.py, polyfactory/value_generators/constrained_dates.py, tests/sqlalchemy_factory/test_sqlalchemy_factory_common.py
=> feat: handle SQLA column constraints

polyfactory/factories/sqlalchemy_factory.py, polyfactory/field_meta.py, polyfactory/utils/types.py, tests/sqlalchemy_factory/test_sqlalchemy_factory_common.py, tests/utils/test_frozendict.py
- Constraints should be hashable to handle downstream usage
- Create `Frozendict` to hold constraints
- Alternative approachs
- Update to vendor in `annotated-types`-esque classes and change internal to support this and use factories per type to generate. This would be backwards breaking and hard to generate for a user.
- Pass constraints separately or another way. Not sure if can do this and pass these to `FieldMeta` whilst not breaking exposed interface
- Fixes #601
=> fix: handle nullable SQLA constraints

.github/workflows/ci.yml
=> fix: lock PDM version to support 3.8

.pre-commit-config.yaml, pdm.lock, polyfactory/factories/pydantic_factory.py, pyproject.toml, tests/test_data_parsing.py, tests/test_pydantic_factory.py, tests/test_random_seed.py
- Update lock file to target Pydantic 2.10
- Support `default_factory` with single arg
- Fix support for URL. These are now distinct types so need specifying in provider map
- Fix typing issues
- Closes #610
=> fix: Pydantic 2.10 compatibility

polyfactory/factories/pydantic_factory.py
- Fixes issue described https://github.com/litestar-org/polyfactory/discussions/576
- Tested with script
```
(polyfactory) ➜  polyfactory git:(perf-refactor-pydantic-imports) ✗ cat test.sh 
#!/usr/bin/env sh
.venv-fast/bin/python -m pip install -e . 
.venv-fast/bin/python -m pip install "pydantic<2.5.0"
.venv-slow/bin/python -m pip install -e . 
.venv-slow/bin/python -m pip install "pydantic==2.5.0"
.venv-slow/bin/python t.py
.venv-fast/bin/python t.py
```
with before and after this change
```
0.22203758300747722
0.1394521670008544
---
0.1482207500084769
0.13731049999478273
```
- Explanation here is `pydantic` now performs dynamic imports in some cases so affects performance when using attrs from the module. By importing directly for common attributes we avoid this cost.
=> refactor: update Pydantic imports

polyfactory/factories/base.py, tests/models.py, tests/test_base_factories.py, tests/test_pydantic_factory.py
- `abc.ABC` cannot be instantiated so does not make sense for these to be  considered factory types
- Closes https://github.com/litestar-org/polyfactory/issues/627
=> fix: ensure ABC are not considered a factory type

polyfactory/factories/sqlalchemy_factory.py, tests/sqlalchemy_factory/test_sqlalchemy_factory_common.py
- **an async context manager** has been added in SQLAASyncPersistence class to prevent
```bash
...
raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
The garbage collector is trying to clean up non-checked-in connection <AdaptedConnection <asyncpg.connection.Connection
object>>, which will be terminated.  Please ensure that SQLAlchemy pooled connections are returned to the pool 
explicitly, either by calling ``close()`` or by using appropriate context managers to manage their lifecycle.
sys:1: SAWarning: The garbage collector is trying to clean up non-checked-in connection <AdaptedConnection 
<asyncpg.connection.Connection object>>, which will be terminated.  Please ensure that SQLAlchemy pooled connections are 
returned to the pool explicitly, either by calling …
```
=> fix(sqla_factory): added an async context manager in SQLAASyncPersistence

polyfactory/field_meta.py, tests/test_complex_types.py
- Allow non-hashable types by checking
- Note this would still raise parameter error in some circumstances but does not raise an internal error allowing the user to specify the way to resolve the type
- Closes #639
=> fix: allow non-hashable type args

pyproject.toml
- I've noticed the library is incompatible with low versions of `faker`.
for example, this script won't work
```python
from polyfactory.factories import pydantic_factory
import pydantic
class MyModel(pydantic.BaseModel):
m_id: int
name: str
class Factory(pydantic_factory.ModelFactory[MyModel]):
__model__ = MyModel
print(Factory.build())
```
won't work with version `faker==4.0.0` or lower, due to missing Generator attribute `json`
=> fix(pyproject.toml): dont allow faker version less then 5.0.0

.pre-commit-config.yaml, docs/conf.py, docs/usage/model_coverage.rst, polyfactory/utils/helpers.py, pyproject.toml, tests/test_pytest_plugin.py, uv.lock
- Update prettier precommit by vendoring in now [archived](https://github.com/pre-commit/mirrors-prettier/tree/main) hook and specifying prettier version here.
- This allows specifying version to one that will be supported by runners. This does have the downside of not being updatable via `pre-commit autoupdate`
- Also in this PR, update other pre-commits and linting fixes required from updates
Edit: changed to using the fork https://github.com/pycontribs/mirrors-prettier which is run by org to maintain such packages so overcomes above issues
=> build: update dependencies and ignores

polyfactory/field_meta.py, polyfactory/utils/helpers.py, tests/test_pydantic_factory.py
- See title
Fixes https://github.com/litestar-org/polyfactory/issues/658
=> fix: ignore dataclass types in pydantic field parsing

polyfactory/factories/base.py, polyfactory/factories/pydantic_factory.py, tests/test_new_types.py, tests/test_pydantic_v1_v2.py, tests/test_recursive_models.py
- This updates the typing of `create_factory` so bound is with specified model if provided
-  Previously bound was the factory itself only so bound of returned factory was wrong
- Also adds `args` to build which is ignored. This is not ideal but current implementation of `ModelFactory.build` allows providing an arg and unable to match to the specific and this breaks when fixing other issue with bounding properly.
- I tried fixing this with extra overloads based on if `BaseModel` but this breaks mypy as there are overlapping overloads
- Longer term may want to remove the arg in ModelFactory but avoiding this for now as a breaking change
- Example of now inferred factory here
=> feat: improve create factory typing

docs/examples/handling_custom_types/test_example_3.py, docs/usage/handling_custom_types.rst, polyfactory/factories/base.py, tests/test_provider_map.py
Without modifying the factory class. This enables 3rd party custom types to easily add providers.
=> feat: add_providers to easily add new type provider

polyfactory/value_generators/primitives.py, tests/constraints/test_int_constraints.py, tests/test_number_generation.py
Based on existing implementation and raised issue this feels like a better range and closer to intention.
Fixes #645
=> feat: improve random range

Makefile, polyfactory/collection_extender.py, polyfactory/factories/attrs_factory.py, polyfactory/factories/dataclass_factory.py, polyfactory/factories/msgspec_factory.py, polyfactory/factories/pydantic_factory.py, polyfactory/factories/sqlalchemy_factory.py, polyfactory/factories/typed_dict_factory.py, polyfactory/field_meta.py, polyfactory/value_generators/constrained_numbers.py, tests/constraints/test_frozen_set_constraints.py, tests/constraints/test_get_field_value_constraints.py, tests/constraints/test_list_constraints.py, tests/constraints/test_mapping_constraints.py, tests/constraints/test_set_constraints.py, tests/test_pydantic_v1_v2.py
- Deprecate `FieldMeta.random`. This is unused and keeps this class stateless
- Simplify pydantic meta. Some edge cases here look handled elsewhere so redundant to handle here too
- Deprecate `CollectionExtender` too. This was only used in `FieldMeta` so no longer needed
=> refactor: deprecate FieldMeta.random

polyfactory/factories/base.py, polyfactory/field_meta.py, tests/sqlalchemy_factory/test_sqlalchemy_factory_common.py, tests/test_base_factories.py
- Allow applying provider map to apply to annotated or new types
- This requires updating `FieldMeta` to preserve original type. I do not think this is backwards breaking but happy to hold off to v3 to support this 
- Closes https://github.com/litestar-org/polyfactory/issues/348
=> feat: support new type and annotated mapping

.pre-commit-config.yaml, pyproject.toml
- add toml formatter. Causing annoyances when working locally with format on save configured
- note this works well with uv add 
- also update old ruff rules. ANN101 and ANN104 are removed. TCH renamed to TC
=> ci: add toml formatter

polyfactory/factories/pydantic_factory.py, tests/test_pydantic_v1_v2.py
When using a Pydantic v1 model in a mixed v1/v2 environment (legacy code, you know), `polyfactory` does not handle `pydantic.v1.HttpUrl` and `pydantic.v1.EmailStr` correctly, and treats them as regular `str`.
This PR fixes the error that occurs when running the code below.
```python
from pydantic.v1 import BaseModel, EmailStr, HttpUrl
from polyfactory.factories.pydantic_factory import ModelFactory
class Foobar(BaseModel):
url: HttpUrl
email: EmailStr
class FoobarFactory(ModelFactory[Foobar]): ...
def main():
factory = FoobarFactory()
print(factory.build())
if __name__ == "__main__":
main()
```
=> fix: handle pydantic v1 URL and email correctly

polyfactory/factories/pydantic_factory.py, tests/test_pydantic_factory.py
Call `model_rebuild` when instantiating a `ModelFactory` so that forward references may be replaced with concrete field information (the equivalent is already done for Pydantic V1).
Fixes https://github.com/litestar-org/polyfactory/issues/686.
=> feat: Allow usage of Pydantic models containing forward references

docs/examples/configuration/test_example_11.py, docs/usage/configuration.rst, polyfactory/factories/base.py, polyfactory/factories/pydantic_factory.py, polyfactory/field_meta.py, polyfactory/utils/helpers.py, polyfactory/utils/predicates.py, tests/test_recursive_models.py, tests/test_type_coverage_generation.py
- Handling of union and recursive types changed slightly with https://github.com/litestar-org/polyfactory/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aclosed
- Update to handle forward ref explicitly
Closes #725
=> fix: handle recursive types that use ForwardRef

polyfactory/factories/pydantic_factory.py, tests/test_pydantic_factory.py
- Fix alias handling for 2.22
- This is regression from [normalisation introduced here](https://github.com/litestar-org/polyfactory/commit/c7a7b4426126d0134d531fc4db34199d39c46298) that meant alias is not propagated. 
- This is slightly hack to focus this but fine before can cleanup this logic with https://github.com/litestar-org/polyfactory/issues/713
Closes https://github.com/litestar-org/polyfactory/issues/736
=> fix: pydantic alias handling

polyfactory/factories/base.py, polyfactory/factories/beanie_odm_factory.py, polyfactory/field_meta.py, tests/test_recursive_models.py
- Fix handling in some case for Pydantic where things resolve to string rather than forward refs. 
- Note this is slightly hard to test via ci as requiring dropping 3.8 to show breakage on newest pydantic version
- Running locally this works where failed previously on main
Closes https://github.com/litestar-org/polyfactory/issues/733
=> fix: allow specifying forward references when as string

polyfactory/factories/pydantic_factory.py
- This PR aims to fix alias generation. This is due to `populate_by_name` config attribute being deprecated by Pydantic from version 2.11
Closes #717
=> fix: Pydantic Factory alias generation from version 2.11
