litestar-org/polyfactory

- .pre-commit-config.yaml
- CHANGELOG.md
- pydantic_factories/extensions/beanie_odm.py
- pydantic_factories/factory.py
- pydantic_factories/protocols.py
- pydantic_factories/utils.py
- pydantic_factories/value_generators/complex_types.py
- tests/test_dataclass.py
- tests/test_factory_options.py
This PR adds support for dataclasses
> Add Dataclass Support

- .gitignore
- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- poetry.lock
- pydantic_factories/factory.py
- pydantic_factories/utils.py
- pyproject.toml
- tests/test_factory_options.py
This PR addresses #10, see the CHANGELOG.md for details
> Update optionals handling

- README.md
- pydantic_factories/constraints/constrained_collection_handler.py
- pydantic_factories/extensions/ormar_orm.py
- pydantic_factories/factory.py
- pydantic_factories/utils.py
- pydantic_factories/value_generators/complex_types.py
- pydantic_factories/value_generators/constrained_number.py
- pydantic_factories/value_generators/primitives.py
- tests/test_factory_options.py
#18 
Added random instance to utils module and used it everwhere random is used
> Custom random instance for determined generation outside of Faker scope

- README.md
Simple example of the Create Factory method so you can create a Generic Factory
> Docs: Added Create Factory Method

- pydantic_factories/constraints/constrained_decimal_handler.py
- tests/constraints/test_decimal_constraints.py
Hi, I read this issue about the constrained_decimal_handler (https://github.com/Goldziher/pydantic-factories/issues/31). 
I had some free-time and really like pydantic-factories. So I thought I might make a contribution to a fix. Let me know if I need to change anything.
> Fix bug constrained decimal handler

- CHANGELOG.md
- pydantic_factories/factory.py
- tests/test_factory_child_models.py
> Fix error when building with a parameter that is a optional pydantic model [Issue #56]

- CHANGELOG.md
- poetry.lock
- pydantic_factories/constraints/constrained_decimal_handler.py
- pyproject.toml
- tests/constraints/test_decimal_constraints.py
> #57 - fix decimal validation

- .pre-commit-config.yaml
- CHANGELOG.md
- poetry.lock
- pydantic_factories/factory.py
- pyproject.toml
> Issue #68: UUID random-seed

- .pre-commit-config.yaml
- CHANGELOG.md
- pydantic_factories/factory.py
- pydantic_factories/value_generators/complex_types.py
- pyproject.toml
- tests/test_dicts.py
> Fix passing nested dicts with pydantic models as values

- CHANGELOG.md
- pydantic_factories/utils.py
- pyproject.toml
- tests/test_discriminated_unions.py
This PR adds support for discriminated unions. It resolves #75
> Add support for discriminated unions

- .github/workflows/ci.yaml
- docs/index.md
- poetry.lock
- pydantic_factories/factory.py
- tests/test_factory_options.py
> Expose 'get_faker'

- pyproject.toml
As @Goldziher requested I am creating a PR to add myself to the maintainer list
> Add Konstantin Mikhailov as a maintainer

- pydantic_factories/constraints/collection.py
- pydantic_factories/factory.py
- pydantic_factories/utils.py
- tests/test_constrained_attribute_parsing.py
- tests/test_new_types.py
- tests/test_utils.py
> Add NewType support

- pydantic_factories/constraints/collection.py
- tests/constraints/test_list_constraints.py
> Add unique_items support for conlist

- pydantic_factories/value_generators/constrained_number.py
- tests/constraints/test_decimal_constraints.py
- tests/constraints/test_float_constraints.py
- tests/constraints/test_int_constraints.py
> Fix ranges support in conint

- pydantic_factories/constraints/decimal.py
- pydantic_factories/constraints/float.py
- pydantic_factories/constraints/integer.py
- pydantic_factories/utils.py
- pydantic_factories/value_generators/constrained_number.py
- tests/constraints/test_decimal_constraints.py
- tests/constraints/test_float_constraints.py
- tests/constraints/test_int_constraints.py
- tests/test_utils.py
This PR closes #118 and #120
It is not ready yet, for some reason i get pyright errors locally so at the moment I only want to test it in CI before continuing writing tests
> Add checks that given number range is valid

- pydantic_factories/factory.py
- tests/test_factory_auto_registration.py
This PR Implement https://github.com/starlite-api/pydantic-factories/issues/115
Here I use __init_subclass__ class method to auto-register created model factories.
> Implement auto registration hook

- docs/usage/4-defining-factory-fields.md
> Add __auto_register__ flag docs

- .github/workflows/ci.yaml
- .gitignore
- .pre-commit-config.yaml
- polyfactory/factories/base.py
- polyfactory/pytest_plugin.py
- polyfactory/value_generators/constrained_dates.py
- polyfactory/value_generators/constrained_numbers.py
- polyfactory/value_generators/regex.py
- pyproject.toml
- tests/test_dataclass_factory.py
- tests/test_faker_customization.py
Migrate to [ruff](https://beta.ruff.rs/docs/) for linting, ci
Closes #151
> Migrate to ruff

- .pre-commit-config.yaml
- docs/conf.py
- docs/index.rst
- docs/reference/constants.rst
- docs/reference/exceptions.rst
- docs/reference/factories/base.rst
- docs/reference/factories/dataclass_factory.rst
- docs/reference/factories/index.rst
- docs/reference/factories/typed_dict_factory.rst
- docs/reference/field_meta.rst
- docs/reference/fields.rst
- docs/reference/persistence.rst
- docs/reference/pytest_plugin.rst
- docs/reference/value_generators/index.rst
- docs/usage/configuration.rst
- docs/usage/declaring_factories.rst
- docs/usage/fields.rst
- docs/usage/fixtures.rst
- docs/usage/library_factories.rst
- poetry.lock
- polyfactory/field_meta.py
- polyfactory/pytest_plugin.py
- polyfactory/value_generators/complex_types.py
- polyfactory/value_generators/constrained_collections.py
- polyfactory/value_generators/constrained_dates.py
- polyfactory/value_generators/constrained_numbers.py
- polyfactory/value_generators/constrained_strings.py
- polyfactory/value_generators/primitives.py
- polyfactory/value_generators/regex.py
- pyproject.toml
- Fix a load of missing references
- Fix `conf.py` typing
- Fix some docstrings
> General documentation updates and fixes

- .github/workflows/ci.yaml
- .github/workflows/publish.yaml
Add a job that validates documentation.
> Validate docs in CI

- docs/reference/constants.rst
> Fix documentation for `polyfactory.constants`

- README.md
- docs/conf.py
- docs/index.rst
- poetry.lock
- Update wording in the introduction / readme
- Update community links
> Update docs pre release

- pyproject.toml
Updated the maintainers list on PyPI and elsewhere.
> chore(meta): update maintainers

- README.md
Fixes an issue with prettier pre-commit hook formatting
> fix(docs): fix README.md formatting

- polyfactory/factories/base.py
- polyfactory/factories/pydantic_factory.py
- tests/test_factory_subclassing.py
Make factory fields inheritable.
> Factory inheritance

- pyproject.toml
> Prepare for `v2.1.0` release

- polyfactory/value_generators/complex_types.py
- tests/test_complex_types.py
> Fix handle_complex_type for Union of Literals

- polyfactory/factories/base.py
- tests/test_provider_map.py
> Correct the Provider Logic

- .pre-commit-config.yaml
- README.md
- poetry.lock
- polyfactory/factories/base.py
- polyfactory/factories/dataclass_factory.py
- polyfactory/factories/msgspec_factory.py
- polyfactory/factories/typed_dict_factory.py
- polyfactory/field_meta.py
- polyfactory/utils/predicates.py
- polyfactory/value_generators/constrained_dates.py
- pyproject.toml
- tests/test_annotated_fields.py
This PR refactors metadata extraction and reduces unnecessary duplication of logic.
> Refactor metadata extraction

- .pre-commit-config.yaml
- poetry.lock
- polyfactory/factories/base.py
- tests/test_base_factories.py
This PR addresses the issue where different base factories get selected.
@gsakkis can you review?
> fix: support overriding base factories locally

- polyfactory/factories/base.py
- pyproject.toml
> Use DEFAULT_RANDOM instead of initializing new value in BaseFactory

- README.md
- poetry.lock
- polyfactory/factories/base.py
- polyfactory/factories/pydantic_factory.py
- polyfactory/factories/typed_dict_factory.py
- polyfactory/field_meta.py
- polyfactory/utils/predicates.py
- polyfactory/value_generators/constrained_numbers.py
- polyfactory/value_generators/primitives.py
- polyfactory/value_generators/regex.py
- tests/constraints/test_get_field_value_constraints.py
- tests/constraints/test_string_constraints.py
- tests/test_constrained_attribute_parsing.py
This PR applies sourcery, addressing all its issues in one go.
> chore: applied sourcery

- polyfactory/factories/base.py
- tests/test_base_factories.py
Follow up to https://github.com/litestar-org/polyfactory/pull/238 as per [this comment](https://github.com/litestar-org/polyfactory/pull/238#discussion_r1243292814).
> fix: support overriding base factories locally (v2)

- polyfactory/factories/msgspec_factory.py
- tests/test_msgspec_factory.py
Trying to use a factory for a model that inherits other models raises an error. This PR fixes this error. 
> Fix inheritance support for msgspec

- .pre-commit-config.yaml
- poetry.lock
- polyfactory/factories/pydantic_factory.py
- polyfactory/factories/typed_dict_factory.py
- polyfactory/field_meta.py
- polyfactory/utils/helpers.py
- pyproject.toml
- tests/test_pydantic_factory.py
This PR adds a *passing* test for issue #300, which demonstrates it cannot be reproduced.
> chore(tests): add passing test for issue 300

- .github/workflows/ci.yaml
- .github/workflows/publish.yaml
- .pre-commit-config.yaml
- CONTRIBUTING.rst
- poetry.lock
- polyfactory/factories/pydantic_factory.py
- pyproject.toml
This PR moves all dev dependencies that are also optional dependencies in the extras group.
> chore(infra): update poetry dependencies

- CONTRIBUTING.rst
> chore(docs): Fix CONTRIBUTING.rst

- polyfactory/factories/pydantic_factory.py
- polyfactory/field_meta.py
- tests/test_annotated_fields.py
This PR fixes a bug where generatic types with Annotated where not parsed for constraints.
> chore(internal): fix annotated field resolution

- .github/CODEOWNERS
> infra: update codeowners

- polyfactory/factories/pydantic_factory.py
- tests/test_pydantic_factory.py
- add support for `Json` type in Pydantic factory
- resolves #302
> fix: add support for Json type in Pydantic factory

- .github/ISSUE_TEMPLATE/BUG.yaml
- .github/ISSUE_TEMPLATE/DOCS.yaml
- .github/ISSUE_TEMPLATE/REQUEST.yaml
- fixes issue health files that were defaulted from the .github repo, these were removed apparently when I added config.yml 
-
> infra: fix health files

- docs/examples/configuration/test_example_1.py
- docs/examples/configuration/test_example_2.py
- docs/examples/configuration/test_example_3.py
- polyfactory/factories/base.py
- pyproject.toml
- tests/test_random_configuration.py
- fix the configuration of the random seed and the corresponding examples
> fix: random seed configuration

- .github/workflows/ci.yaml
- polyfactory/factories/pydantic_factory.py
- fix the `MissingDependencyError` when using pydantic v1
- fix the tests to remove pydantic_core when testing pydantic v1
- Fixes #328
> fix: fix pydantic core import

- docs/examples/configuration/test_example_3.py
- polyfactory/factories/base.py
- tests/test_random_configuration.py
- override the seed on the existing Faker instance instead of a new one
- fixes #330
> fix: ensure no override of Faker instance

- polyfactory/factories/base.py
- polyfactory/value_generators/constrained_collections.py
- tests/constraints/test_mapping_constraints.py
- tests/test_msgspec_factory.py
- This PR introduces support for handling constrained `Mapping` types such as dictionaries.
- Fixes #326
> feat: support constraints for mapping types

- README.md
- pyproject.toml
> chore(release): prepare for v2.8.0

- .all-contributorsrc
- docs/conf.py
- docs/examples/configuration/test_example_7.py
- docs/usage/configuration.rst
- Exposes all special members for API docs except `__init_subclass__`, `__subclass_hook__` and  `__weakref__`.
- Add example for `__allow_none_optionals__`.
- Closes #336
> docs: Expose all options

- .all-contributorsrc
- polyfactory/factories/base.py
- This PR adds the missing factories (msgspec and attrs factories) to the default builtin factory registration.
> fix: add missing factories to builtin registration

- .all-contributorsrc
- poetry.lock
- pyproject.toml
> chore: prepare v2.8.1

- Makefile
- Fixes an issue with the makefile not setting the right vars
> fix(infra): update makefile

- .github/workflows/docs.yaml
- Update installation to all so pages that require third party packages are rendered properly.
- Fixes #401
> docs: Install all dependencies for docs build

- pyproject.toml
> chore: prepare for releasing v2.10

- .github/workflows/ci.yaml
- .github/workflows/publish.yaml
- Same fix as https://github.com/litestar-org/polyfactory/pull/404 but in other places.
- Fixes #401
> docs: Update installation

- polyfactory/field_meta.py
- tests/constraints/test_get_field_value_constraints.py
- This PR enables annotating any types with `Constraints` to specify the constraints. It is important to note that this does NOT mean that these constraints will be validated at runtime, but that `polyfactory` will take them into account when creating the model instances.
> feat: support annotation with Constraints

- docs/examples/fields/test_example_8.py
- docs/usage/fields.rst
- docs/usage/index.rst
> docs: Reorder docs. Add docs on Factories as fields

- pdm.lock
- pyproject.toml
- update the dependencies
- update the version
> chore(release): prepare for v2.12.0

- .pre-commit-config.yaml
- polyfactory/factories/attrs_factory.py
- tests/test_beanie_factory.py
- add `attrs` as a dependency for `mypy` and `pyright`
- remove unused `type: ignore` comments
> chore: update pre commit

- CONTRIBUTING.rst
- replace broken uri with valid one
-
> docs: fix broken uri

- polyfactory/factories/sqlalchemy_factory.py
- tests/sqlalchemy_factory/test_sqlalchemy_factory_common.py
> fix: ignore non-columns types

- docs/changelog.rst
- pyproject.toml
Fix (150) URL typos
Of the +600 links to github in changelog, 150 of them are wrong, which I assume was unintended? 
It raises the question: are these links machine inserted?
> chore: Update changelog.rst

- polyfactory/factories/base.py
- tests/test_factory_fields.py
- Copy mutable values to avoid instance being reused between created instances
- Using hashability for as test, as done with dataclasses
> feat: copy mutable args

- pyproject.toml
- Update the emails of the maintainers.
- Add @Alc-Alc as maintainer.
> chore: update maintainer emails

- docs/changelog.rst
- pyproject.toml
> chore(release): prepare for v2.16.0

- .github/workflows/ci.yml
- Bump the patch version of pydantic to fix an issue on the CI
> chore(test): bump pydantic

- polyfactory/factories/base.py
- polyfactory/factories/pydantic_factory.py
- polyfactory/value_generators/complex_types.py
- tests/test_pydantic_factory.py
`ModelFactory._create_model` not handling _build_context = None
#563
> fix: Nested model in collection build context

- docs/examples/fixtures/test_example_1.py
- polyfactory/pytest_plugin.py
Enhance `register_fixture` return type annotation instead of using `Any`.
-
Closes #579
> feat(#579): enhance register_fixture return type annotation

- .github/workflows/ci.yml
- polyfactory/value_generators/constrained_dates.py
> fix: update docs preview upload

- .github/workflows/ci.yml
- pdm.lock
- polyfactory/value_generators/constrained_dates.py
- pyproject.toml
- Local testing currently fails on SQLA async tests.
- Update dependencies to fix this
> fix: add SQLA async to test dependencies

- .github/workflows/ci.yml
- This action is deprecated https://github.com/sonarsource/sonarcloud-github-action/tree/master/
> build: change deprecated action

- docs/changelog.rst
- pyproject.toml
- uv.lock
> chore: prep 2.19.0 release

- .pre-commit-config.yaml
- polyfactory/factories/base.py
- polyfactory/factories/pydantic_factory.py
- polyfactory/pytest_plugin.py
- polyfactory/utils/model_coverage.py
- polyfactory/value_generators/complex_types.py
- pyproject.toml
- tests/sqlalchemy_factory/test_sqlalchemy_factory_v2.py
- tests/test_beanie_factory.py
- tests/test_odmantic_factory.py
- Remove warning from test run for `pytest-asyncio` https://github.com/pytest-dev/pytest-asyncio/issues/924#issuecomment-2321921915
- Simplify test imports by removing conditions. This isn't done elsewhere in this project and may cause issues by never reporting tests failing as may never run if CI env is not set up correctly
> chore: improve test imports

- .pre-commit-config.yaml
- polyfactory/factories/sqlalchemy_factory.py
- Previously I did not update pyright due to type errors emitted
- Updated now and including solution based on https://github.com/microsoft/pyright/discussions/10116#discussioncomment-12554130
> build: update pyright

- docs/changelog.rst
- pyproject.toml
- uv.lock
> chore: prep 2.20.0 release

- docs/examples/library_factories/sqlalchemy_factory/test_example_5.py
- docs/usage/library_factories/sqlalchemy_factory.rst
- polyfactory/factories/sqlalchemy_factory.py
- tests/sqlalchemy_factory/test_sqlalchemy_factory_common.py
- Sign post and document cases where cannot map automatically
> feat: document overriding SQLA column mapping

- .pre-commit-config.yaml
- tests/sqlalchemy_factory/models.py
- tests/sqlalchemy_factory/test_sqlalchemy_factory_common.py
- tests/sqlalchemy_factory/test_sqlalchemy_factory_v2.py
- tests/test_msgspec_factory.py
- tests/test_pydantic_v1_v2.py
- tests/test_recursive_models.py
- tests/test_type_coverage_generation.py
- typos.toml
> refactor: migrate to typos

- .github/workflows/docs.yml
- CONTRIBUTING.rst
- Makefile
- pyproject.toml
- tools/prepare-release.sh
- uv.lock
- This PR automates some of the release process by create changelog and release commit
- This adds `bump-my-version` to align with other litestar repos and updates `git-cliff` command to use `gh auth` to allow running without specifying token
- Alternative approaches would be porting release script from other repos. Omitting this for now to avoid restructuring too much but happy to adopt those if preferable
> feat: add release command

- docs/changelog.rst
- pyproject.toml
- uv.lock
> chore(release): bump to v2.21.0

- polyfactory/utils/predicates.py
- see https://github.com/python/typing_extensions/issues/586
> chore: remove usage of _AnnotatedAlias

- polyfactory/factories/pydantic_factory.py
- polyfactory/value_generators/constrained_collections.py
- tests/test_collection_length.py
Fixes a bug where annotation_types.Len can go over the described length
```
================================================ short test summary info ================================================
FAILED tests/test_collection_length.py::test_annotated_type_collection_length[1-List] - AssertionError: 2
FAILED tests/test_collection_length.py::test_annotated_type_collection_length[1-Dict] - AssertionError: 2
FAILED tests/test_collection_length.py::test_annotated_type_collection_length[2-List] - AssertionError: 3
FAILED tests/test_collection_length.py::test_annotated_type_collection_length[2-Dict] - AssertionError: 3
FAILED tests/test_collection_length.py::test_annotated_type_collection_length[3-List] - AssertionError: 4
FAILED tests/test_collection_length.py::test_annotated_type_collection_l …
```
> fix: Generate correct collection size when annotation_types.Len is used

- docs/changelog.rst
- pyproject.toml
- uv.lock
> chore(release): bump to v2.22.0
